# Generated by Django 4.1.4 on 2023-10-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_product_quantity_alter_product_category_and_more'),
        ('volunteers', '0003_rename_user_volunteer_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='stores.order')),
                ('requester', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteer')),
            ],
        ),
    ]
