# Generated by Django 4.2.6 on 2023-10-14 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donations.extendeduser'),
        ),
        migrations.AddField(
            model_name='donation',
            name='expiry_date',
            field=models.DateField(default='2025-10-10'),
        ),
        migrations.AddField(
            model_name='donation',
            name='food_type',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.CharField(default='10', max_length=100),
        ),
    ]
