# Generated by Django 4.1.4 on 2023-10-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(default='Edible', max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('donation_date', models.DateField()),
            ],
        ),
    ]
